### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by terryjentsch** [amin-nejat/fcf#5]
I just wanted to let you know that some of your documentations are not corresponding to the in and outputs of your functions. For example in delay_embedding/ccm.py the connectivity function has three returns but only two are documented. 

furthermore, regarding this function I would like to know how the resulting fcf matrix is structured. How I understood it the rows should represent how well the corresponding channel can predict all other channels while a column should represent how well each channel can be predicted by every other channel. Is this a valid interpretation? And if so, is it the right way around or do I need to exchange row and columns?

**Comment by amin-nejat** [comment]
Thanks for bringing up this issue, I'll fix the documentation as soon as possible. To answer your question, indeed rows correspond to how well channel i can predict/reconstruct other channels. One way to think about it that if (i,j) has a large value compared to (j,i) then i is downstream of j because j has more information about i.

Regarding the third output, we follow twin surrogates method and create a surrogate dataset based on the neighborhood structure of the data. Using fcf on the surrogate dataset we compute the p-value of each entry of the original fcf matrix.

**Comment by amin-nejat** [comment]
Resolved
